//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodki
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD10_Счет
    {
        public string Код_счета { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public string Settled { get; set; }
        public string Сумма { get; set; }
        public string Сумма_НДС { get; set; }
        public string Дата { get; set; }
    
        public virtual BD10_Заказ BD10_Заказ { get; set; }
    }
}
