//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodki
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD10_Доставка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BD10_Доставка()
        {
            this.BD10_Заказ = new HashSet<BD10_Заказ>();
            this.BD10_Критерии_доставки = new HashSet<BD10_Критерии_доставки>();
        }
    
        public int Код_доставки { get; set; }
        public string Дата { get; set; }
        public Nullable<int> Код_менеджера { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Код_лодки { get; set; }
        public string Адрес_доставки { get; set; }
        public string Город { get; set; }
    
        public virtual BD10_Лодка BD10_Лодка { get; set; }
        public virtual BD10_Менеджеры BD10_Менеджеры { get; set; }
        public virtual BD10_Покупатель BD10_Покупатель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD10_Заказ> BD10_Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD10_Критерии_доставки> BD10_Критерии_доставки { get; set; }
    }
}
