//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodki
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD10_Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BD10_Заказ()
        {
            this.BD10_Счет = new HashSet<BD10_Счет>();
        }
    
        public int Код_заказа { get; set; }
        public Nullable<int> Дата { get; set; }
        public Nullable<System.DateTime> Внесенный_депозит { get; set; }
        public Nullable<int> Код_доставки { get; set; }
        public string Общая_сумма { get; set; }
        public string Общая_сумма_с_НДС { get; set; }
        public Nullable<System.DateTime> Разработка_продукта { get; set; }
    
        public virtual BD10_Доставка BD10_Доставка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD10_Счет> BD10_Счет { get; set; }
    }
}
