//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodki
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD10_Лодка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BD10_Лодка()
        {
            this.BD10_Доставка = new HashSet<BD10_Доставка>();
            this.BD10_Лодочные_аксессуары = new HashSet<BD10_Лодочные_аксессуары>();
        }
    
        public int Код_лодки { get; set; }
        public string Модель { get; set; }
        public string Тип_лодки { get; set; }
        public string Количество_мест_дл_грибунов { get; set; }
        public string Мачта { get; set; }
        public string Цвет { get; set; }
        public string Дерево { get; set; }
        public string Базовая_цена { get; set; }
        public string НДС { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD10_Доставка> BD10_Доставка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD10_Лодочные_аксессуары> BD10_Лодочные_аксессуары { get; set; }
    }
}
