//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodki
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user84_dbEntities : DbContext
    {
        public user84_dbEntities()
            : base("name=user84_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BD10_Аксессуары> BD10_Аксессуары { get; set; }
        public virtual DbSet<BD10_Доставка> BD10_Доставка { get; set; }
        public virtual DbSet<BD10_Заказ> BD10_Заказ { get; set; }
        public virtual DbSet<BD10_Критерии_доставки> BD10_Критерии_доставки { get; set; }
        public virtual DbSet<BD10_Лодка> BD10_Лодка { get; set; }
        public virtual DbSet<BD10_Лодочные_аксессуары> BD10_Лодочные_аксессуары { get; set; }
        public virtual DbSet<BD10_Менеджеры> BD10_Менеджеры { get; set; }
        public virtual DbSet<BD10_Партнеры> BD10_Партнеры { get; set; }
        public virtual DbSet<BD10_Покупатель> BD10_Покупатель { get; set; }
        public virtual DbSet<BD10_Счет> BD10_Счет { get; set; }
        public virtual DbSet<BD10_Пользователь> BD10_Пользователь { get; set; }
    }
}
